# Generated by Django 5.1.3 on 2024-12-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
