# Generated by Django 5.1.3 on 2024-12-01 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('portal', '0002_knowledgebase_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.bot'),
        ),
    ]
