# Generated by Django 5.1.3 on 2024-12-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
