# Generated by Django 5.1.3 on 2024-12-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_knowledgebase_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebasedocument',
            name='knowledge_base',
        ),
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
        migrations.DeleteModel(
            name='KnowledgeBaseDocument',
        ),
    ]
