# Generated by Django 5.1.3 on 2025-01-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='portal.company'),
        ),
        migrations.AddField(
            model_name='bottemplate',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.bot'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='chatbot.bot'),
        ),
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chatbot.knowledgebase'),
        ),
        migrations.AddField(
            model_name='bot',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='chatbot.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgebase',
            unique_together={('collection_name', 'bot')},
        ),
    ]
