# Generated by Django 5.1.3 on 2024-12-22 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_bottemplate'),
        ('portal', '0004_remove_knowledgebasedocument_knowledge_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='portal.company'),
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('knowledge_base_type', models.IntegerField(choices=[(1, 'Document'), (2, 'URL')])),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.bot')),
            ],
            options={
                'unique_together': {('collection_name', 'bot')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chatbot.knowledgebase')),
            ],
        ),
    ]
