# Generated by Django 5.1.3 on 2025-02-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_deployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_tokens', models.IntegerField()),
                ('context_window', models.IntegerField()),
                ('license_type', models.CharField(max_length=100)),
                ('license_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
                ('token_limit', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.aimodel')),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.bot')),
            ],
        ),
        migrations.DeleteModel(
            name='BotTemplate',
        ),
    ]
