# Generated by Django 5.1.3 on 2024-12-22 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_bot_company_knowledgebase_knowledgebasedocument'),
        ('portal', '0004_remove_knowledgebasedocument_knowledge_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='portal.company'),
        ),
    ]
