# Generated by Django 5.1.3 on 2025-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_aimodel_botsetting_delete_bottemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
