# Generated by Django 5.1.3 on 2024-12-23 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_tag_bot_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='chatbot.bot'),
        ),
    ]
